/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.MedicalInventoryAdminWorkArea;


import CarrierAgency.DeliveryAgency;
import CarrierAgency.DeliveryAgencyDirectory;
import Hospital.Hospital.Hospital;
import Warehouse.MedSupInven.MedSupEquip;
import Warehouse.MedSupInven.MedSupEquipDirectory;
import System.MedicalServiceCentralisationEcoSystem;
import System.UserAccount;
import System.UserAccountDirectory;
import Warehouse.MedSupWarehouse;
import Warehouse.MedSupWarehouseDirectory;
import Warehouse.Orders.Order;
import Warehouse.Orders.OrderDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sarth
 */
public class MedSupWarehouseOrderDatabase extends javax.swing.JPanel {

    /**
     * Creates new form OperationalAccountsPage
     */
    JPanel userProcessContainer;
    MedicalServiceCentralisationEcoSystem medicalServiceCentralisationEcoSystem;
    UserAccount userAccount;
    UserAccountDirectory userAccountDirectory;
//    PatientMedSupEquipDirectory patientMedSupEquipDirectory;
    MedSupEquipDirectory medSupEquipDirectory;
    MedSupWarehouse medSupWarehouseCurrent;
    
    public MedSupWarehouseOrderDatabase(JPanel userProcessContainer , MedicalServiceCentralisationEcoSystem medicalServiceCentralisationEcoSystem, MedSupWarehouse medSupWarehouse) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.medicalServiceCentralisationEcoSystem = medicalServiceCentralisationEcoSystem;
        this.medSupWarehouseCurrent = medSupWarehouse;
        
        addneworderstotable();
        populateDeliveryAgency();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jButtonHome = new javax.swing.JButton();
        jButtonAssignDeliveryAgency = new javax.swing.JButton();
        jLabelTitle2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNewOrders = new javax.swing.JTable();
        jLabelPatientName1 = new javax.swing.JLabel();
        jComboBoxDeliveryAgency = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("New Orders");
        add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 706, -1));

        jButtonHome.setBackground(new java.awt.Color(255, 255, 204));
        jButtonHome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonHome.setText("HOME");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        add(jButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 70, 110, 60));

        jButtonAssignDeliveryAgency.setBackground(new java.awt.Color(255, 255, 204));
        jButtonAssignDeliveryAgency.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAssignDeliveryAgency.setText("ASSIGN");
        jButtonAssignDeliveryAgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAssignDeliveryAgencyActionPerformed(evt);
            }
        });
        add(jButtonAssignDeliveryAgency, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 110, 60));

        jLabelTitle2.setFont(new java.awt.Font("Times New Roman", 1, 56)); // NOI18N
        jLabelTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle2.setText("Medical Supplies Order Database");
        add(jLabelTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 920, -1));

        jTableNewOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Medical Equipment Names", "Medical Equipment Total Price", "Hospital ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableNewOrders);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 810, 110));

        jLabelPatientName1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPatientName1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPatientName1.setText("Delivery Agency");
        add(jLabelPatientName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 378, 160, -1));

        jComboBoxDeliveryAgency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        add(jComboBoxDeliveryAgency, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        MedSupWarehouseAdminWorkAreaJPanel medSupWarehouseAdminWorkAreaJPanel = new MedSupWarehouseAdminWorkAreaJPanel(userProcessContainer,medicalServiceCentralisationEcoSystem, medSupWarehouseCurrent);
        userProcessContainer.add("medSupWarehouseAdminWorkAreaJPanel",medSupWarehouseAdminWorkAreaJPanel);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.show(userProcessContainer,"medSupWarehouseAdminWorkAreaJPanel");
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonAssignDeliveryAgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAssignDeliveryAgencyActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableNewOrders.getModel();
        int selected_row_ix = jTableNewOrders.getSelectedRow();
        Order order = (Order) model.getValueAt(selected_row_ix, 0);
        String delivery_agency_id = (String) jComboBoxDeliveryAgency.getSelectedItem();
        order.setDelivery_agency_id(delivery_agency_id);
        
    }//GEN-LAST:event_jButtonAssignDeliveryAgencyActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAssignDeliveryAgency;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JComboBox<String> jComboBoxDeliveryAgency;
    private javax.swing.JLabel jLabelPatientName1;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitle2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNewOrders;
    // End of variables declaration//GEN-END:variables


    private void addneworderstotable() {
        
        OrderDirectory orderDirectory = medSupWarehouseCurrent.getOrderDirectory();
        ArrayList<Order> orderList = orderDirectory.getOrderList();
        DefaultTableModel model = (DefaultTableModel) jTableNewOrders.getModel();
        model.setRowCount(0);
//        DefaultComboBoxModel dc = new DefaultComboBoxModel();
        
        for(Order order: orderList)
        {
            if(order.getStatus().equals("new")){
                model.addRow(new Object[]{order, order.getMedSupEquipItemsWithQuantity(), order.getOrder_amount(),order.getWarehouseId()});
            }
        }
        jTableNewOrders.setModel(model);
    }

    private void populateDeliveryAgency() {
        DeliveryAgencyDirectory deliveryAgencyDirectory = medicalServiceCentralisationEcoSystem.getDeliveryAgencyDirectory();
        ArrayList<DeliveryAgency> deliveryAgencyList = deliveryAgencyDirectory.getDeliveryAgencyList();
        for(DeliveryAgency deliveryAgency: deliveryAgencyList){
            jComboBoxDeliveryAgency.addItem(deliveryAgency.getDeliveryAgencyId());
        }
    }
}
