/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ent_Login;

/**
 *
 * @author animeshgiri
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        CatCompBtn = new javax.swing.JPanel();
        CustRegBtn = new javax.swing.JButton();
        HotelBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        SupplierBtn = new javax.swing.JButton();
        CorpBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setDividerLocation(100);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        CatCompBtn.setBackground(new java.awt.Color(0, 153, 204));

        CustRegBtn.setText("Customer");
        CustRegBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustRegBtnActionPerformed(evt);
            }
        });

        HotelBtn.setText("Hotel");
        HotelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HotelBtnActionPerformed(evt);
            }
        });

        jButton3.setText("Catering Company");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        SupplierBtn.setText("Supplier");
        SupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierBtnActionPerformed(evt);
            }
        });

        CorpBtn.setText("Corporation");
        CorpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorpBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CatCompBtnLayout = new javax.swing.GroupLayout(CatCompBtn);
        CatCompBtn.setLayout(CatCompBtnLayout);
        CatCompBtnLayout.setHorizontalGroup(
            CatCompBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CatCompBtnLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(CustRegBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(HotelBtn)
                .addGap(133, 133, 133)
                .addComponent(jButton3)
                .addGap(132, 132, 132)
                .addComponent(SupplierBtn)
                .addGap(124, 124, 124)
                .addComponent(CorpBtn)
                .addGap(118, 118, 118))
        );
        CatCompBtnLayout.setVerticalGroup(
            CatCompBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CatCompBtnLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(CatCompBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustRegBtn)
                    .addComponent(HotelBtn)
                    .addComponent(jButton3)
                    .addComponent(SupplierBtn)
                    .addComponent(CorpBtn))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        splitPane.setTopComponent(CatCompBtn);

        jPanel1.setBackground(new java.awt.Color(0, 218, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1209, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierBtnActionPerformed
        // TODO add your handling code here:
        SupplierJPanel supplierPanel = new SupplierJPanel();
        splitPane.setRightComponent(supplierPanel);
    }//GEN-LAST:event_SupplierBtnActionPerformed

    private void HotelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HotelBtnActionPerformed
        // TODO add your handling code here:
        HotelJPanel hotelPanel = new HotelJPanel();
        splitPane.setRightComponent(hotelPanel);
    }//GEN-LAST:event_HotelBtnActionPerformed

    private void CustRegBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustRegBtnActionPerformed
        // TODO add your handling code here:
        CustomerJPanel customerPanel = new CustomerJPanel(splitPane);
        splitPane.setRightComponent(customerPanel);
    }//GEN-LAST:event_CustRegBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CatererJPanel catererPanel = new CatererJPanel();
        splitPane.setRightComponent(catererPanel);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CorpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorpBtnActionPerformed
        // TODO add your handling code here:
        CorporationJPanel corporationPanel = new CorporationJPanel();
        splitPane.setRightComponent(corporationPanel);
    }//GEN-LAST:event_CorpBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CatCompBtn;
    private javax.swing.JButton CorpBtn;
    private javax.swing.JButton CustRegBtn;
    private javax.swing.JButton HotelBtn;
    private javax.swing.JButton SupplierBtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
