/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.CustomerAssistanceTeam.CustomerAssistanceRepresentativeWorkArea;



import System.MedicalServiceCentralisationEcoSystem;

import CustomerAssistanceTeam.CustomerAssistanceRepresentative.CustomerSupportMemberDirectory;
import CustomerAssistanceTeam.CustomerAssistanceRepresentative.CustomerSupportMember;
import CustomerAssistanceTeam.CustomerSupportTeam;
import Hospital.Hospital.Hospital;
import Hospital.Hospital.HospitalDirectory;
import Hospital.Requests.Request;
import Hospital.Requests.RequestDirectory;


import System.Role.CustomerSupportMemberRole;
import System.Role.FrontDeskOperatorRole;
import System.Role.Role;

import System.UserAccount;
import System.UserAccountDirectory;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sarth
 */
public class CustomerAssistanceRepresentativeWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OperationalAccountsPage
     */
    JPanel userProcessContainer;
    MedicalServiceCentralisationEcoSystem medicalServiceCentralisationEcoSystem;
    
    CustomerSupportTeam customerSupportTeam;
    private String request_category;
    Request request;
    private UserAccountDirectory UserAccountDirectory;
    private HospitalDirectory hospitalDirectory;
    public CustomerAssistanceRepresentativeWorkAreaJPanel(JPanel userProcessContainer , MedicalServiceCentralisationEcoSystem medicalServiceCentralisationEcoSystem) {
        
        this.userProcessContainer = userProcessContainer;
        this.medicalServiceCentralisationEcoSystem = medicalServiceCentralisationEcoSystem;
        initComponents();
        
        addrecordstotable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRequests = new javax.swing.JTable();
        jButtonCreate = new javax.swing.JButton();
        jTextFieldCustPhone = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldNotes = new javax.swing.JTextField();
        jTextFieldCustName = new javax.swing.JTextField();
        jLabelEmpID = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();
        jLabelEmpName = new javax.swing.JLabel();
        jRadioButtonMedTest = new javax.swing.JRadioButton();
        jRadioButtonMedEquipment = new javax.swing.JRadioButton();
        jLabelEmpName1 = new javax.swing.JLabel();
        jLabelEmpName2 = new javax.swing.JLabel();
        jTextFieldCustEmail = new javax.swing.JTextField();
        jLabelEmpName3 = new javax.swing.JLabel();
        jTextFieldCustPincode = new javax.swing.JTextField();
        jLabelEmpName5 = new javax.swing.JLabel();
        jDateChooserTestDate = new com.toedter.calendar.JDateChooser();
        bgdimg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 70, 169));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 56)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Assistance Representatives");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1000, -1));

        jTableRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CaseId", "Customer Name", "CustomerPhone", "CustomerEmail", "CustomerPincode", "Request Date", "RequestCategory", "CaseDescription", "Timestamp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRequestsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRequests);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 870, 100));

        jButtonCreate.setBackground(new java.awt.Color(255, 255, 204));
        jButtonCreate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCreate.setText("CREATE");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });
        add(jButtonCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 90, 40));
        add(jTextFieldCustPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 421, -1));

        jButtonUpdate.setBackground(new java.awt.Color(255, 255, 204));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdate.setText("UPDATE");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, 90, 40));

        jLabelPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPassword.setText("Notes");
        add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 88, -1));
        add(jTextFieldNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 403, 65));
        add(jTextFieldCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 421, -1));

        jLabelEmpID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEmpID.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelEmpID.setText("Customer Name");
        add(jLabelEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 150, 20));

        jButtonDelete.setBackground(new java.awt.Color(255, 255, 204));
        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDelete.setText("DELETE");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 570, 90, 40));

        jLabelEmpName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEmpName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelEmpName.setText("Customer Phone");
        add(jLabelEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 252, 160, 20));

        jRadioButtonMedTest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonMedTest.setText("Medical Test");
        jRadioButtonMedTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMedTestActionPerformed(evt);
            }
        });
        add(jRadioButtonMedTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        jRadioButtonMedEquipment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonMedEquipment.setText("Medical equipment");
        jRadioButtonMedEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMedEquipmentActionPerformed(evt);
            }
        });
        add(jRadioButtonMedEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, -1));

        jLabelEmpName1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEmpName1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelEmpName1.setText("Request Category");
        add(jLabelEmpName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 170, 30));

        jLabelEmpName2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEmpName2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelEmpName2.setText("Customer Email");
        add(jLabelEmpName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 150, 20));
        add(jTextFieldCustEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 421, -1));

        jLabelEmpName3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEmpName3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelEmpName3.setText("Customer Pincode");
        add(jLabelEmpName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 180, 20));
        add(jTextFieldCustPincode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 421, -1));

        jLabelEmpName5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEmpName5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelEmpName5.setText("Date ");
        add(jLabelEmpName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 160, 30));
        add(jDateChooserTestDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 170, 30));

        bgdimg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bgdimg.setMaximumSize(new java.awt.Dimension(8095, 5397));
        bgdimg.setMinimumSize(new java.awt.Dimension(8095, 5397));
        bgdimg.setPreferredSize(new java.awt.Dimension(8095, 5397));
        add(bgdimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 1370, 1050));
    }// </editor-fold>//GEN-END:initComponents
    public void raise_request(ArrayList<String> user_input){
        
        DefaultTableModel model = (DefaultTableModel) jTableRequests.getModel();
        
//        UserAccountDirectory usersList = medicalServiceCentralisationEcoSystem.getUserAccountDirectory();
        RequestDirectory requestList = medicalServiceCentralisationEcoSystem.getRequestDirectory();
        System.out.println(requestList.getLast_case_id());
//        userAccount = new UserAccount(user_input.get(0), user_input.get(2),new CustomerSupportMemberRole());
        request = new Request();
        String current_timeStamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new Date());
        String last_case_id = requestList.getLast_case_id();
        int last_case_id_int = Integer.parseInt(last_case_id.replaceAll("[\\D]", ""));
        last_case_id_int++;
        
        request.setCase_id(last_case_id);
        request.setCustomer_name(user_input.get(0));
        request.setCustomer_phone(user_input.get(1));
        request.setCustomer_email(user_input.get(2));
//        request.setHospital_id(user_input.get(3));
        request.setCustomer_pincode(user_input.get(3));
        request.setRequest_date(user_input.get(4));
        request.setRequest_category(user_input.get(5));
        request.setRequest_description(user_input.get(6));
        request.setMode(user_input.get(7));
        request.setModified_time(current_timeStamp);
        request.setRequest_status("new");
        requestList.addRequest(request);
        String last_case_id_new = "REQUEST" + String.format("%03d", last_case_id_int);
        requestList.setLast_case_id(last_case_id_new);
            
        JOptionPane.showMessageDialog(this, "New Request Information has been added.");
        model.addRow(new Object[]{
            request,
            request.getCustomer_name(),
            request.getCustomer_phone(),
            request.getCustomer_email(),
            request.getCustomer_pincode(),
            request.getRequest_date(),
            request.getRequest_category(),
            request.getRequest_description(),
            current_timeStamp});
        clearFields();
        
    }
    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        // TODO add your handling code here:
        
        ArrayList<String> user_input = check_empty_field();
        raise_request(user_input);
        
    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
       int selected_row_ix = jTableRequests.getSelectedRow();

        if(selected_row_ix < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to update.");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) jTableRequests.getModel();
        Request selectedReq = (Request) model.getValueAt(selected_row_ix, 0);
        RequestDirectory requestDirectory = medicalServiceCentralisationEcoSystem.getRequestDirectory();
        ArrayList<Request> requestList = requestDirectory.getRequestList();
  
        for(Request request: requestList)
            {   
                if(request.getCustomer_name().equals(selectedReq.getCustomer_name())) {
                    
                    ArrayList<String> user_input = check_empty_field();
                    
                    model.setValueAt(user_input.get(0), selected_row_ix, 0);
                    model.setValueAt(user_input.get(1), selected_row_ix, 1);
                    model.setValueAt(user_input.get(2), selected_row_ix, 2);
                    model.setValueAt(user_input.get(3), selected_row_ix, 3);
                    model.setValueAt(user_input.get(6), selected_row_ix, 6);
                    
                    requestDirectory.updateReq(set_user_input_values(request, user_input));
                }
                    
                

            }
        JOptionPane.showMessageDialog(this, "Values updated");
        addrecordstotable();    
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private Request set_user_input_values(Request request, ArrayList<String> user_input) {
        request.setCustomer_name(user_input.get(0));
        request.setCustomer_phone(user_input.get(1));
        request.setCustomer_email(user_input.get(2));
        request.setCustomer_pincode(user_input.get(3));
        request.setRequest_description(user_input.get(6));
        
        return request;
    }

      
    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        int selected_row_ix = jTableRequests.getSelectedRow();

        if(selected_row_ix < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }
        RequestDirectory requestList = medicalServiceCentralisationEcoSystem.getRequestDirectory();
        DefaultTableModel model = (DefaultTableModel) jTableRequests.getModel();
        Request selectedReq = (Request) model.getValueAt(selected_row_ix, 0);
        requestList.deleteReq(selectedReq);
        JOptionPane.showMessageDialog(this, "Data Deleted.");
        addrecordstotable();
        clearFields();
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTableRequestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRequestsMouseClicked
        // TODO add your handling code here:
        jButtonCreate.setEnabled(false);
          
        int selected_row_ix = jTableRequests.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTableRequests.getModel();
        
        Request selectedReq = (Request) model.getValueAt(selected_row_ix, 0);
        
        
        jTextFieldCustName.setText(selectedReq.getCustomer_name());
        jTextFieldCustPhone.setText(selectedReq.getCustomer_phone());
        jTextFieldCustEmail.setText(selectedReq.getCustomer_email());
        jTextFieldCustPincode.setText(selectedReq.getCustomer_pincode());
        jTextFieldNotes.setText(selectedReq.getRequest_description());
        
        
   
//        UserAccount select_user_account_details = (UserAccount)model.getValueAt(selected_row_ix, 0);
//        
//        jTextFieldCustName.setText(select_user_account_details.getUsername());
//        //jTextFieldCustPhone.setText(select_user_account_details.getPassword());
//      // jTextFieldCustPhone.setText(select_user_account_details.);
//        Role role = select_user_account_details.getRole();
//        System.out.println("role.toString(): "+role.toString());
//        
//        
////        if(role.toString().equals("CustomerSupportMember")){
////            CustomerSupportTeam customerSupportTeam = select_user_account_details.getCustomerSupportTeam();
//////            accountantDirectory = customerSupportTeam.getCustomerSupportMemberDirectory();
//////            HashMap<String, CustomerSupportMember> accountantList = accountantDirectory.getCustomerSupportMemberList();
////            CustomerSupportMember accountant = accountantList.get(select_user_account_details.getUsername());
////            jTextFieldCustPhone.setText(accountant.getCustomerSupportMemberName());
////        }
//        
//        jTextFieldNotes.setText(select_user_account_details.getPassword());
        
    }//GEN-LAST:event_jTableRequestsMouseClicked

    private void jRadioButtonMedTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMedTestActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonMedTest.isSelected()){
            //jRadioButtonConsultation.setSelected(false);
            jRadioButtonMedEquipment.setSelected(false);
            request_category = "MedicalTest";
        }
    }//GEN-LAST:event_jRadioButtonMedTestActionPerformed

    private void jRadioButtonMedEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMedEquipmentActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonMedEquipment.isSelected()){
            jRadioButtonMedTest.setSelected(false);
            //jRadioButtonConsultation.setSelected(false);
            request_category = "MedicalEquipment";
        }
    }//GEN-LAST:event_jRadioButtonMedEquipmentActionPerformed
//    private UserAccount set_user_input_values(UserAccount userAccount, ArrayList<String> user_input) {
////        userAccount.getEmployee().setEmployee_id(user_input.get(0));
////        userAccount.getEmployee().setEmployee_name(user_input.get(1));
//        userAccount.setPassword(user_input.get(2));
//        return userAccount;
//    }
    private void clearFields(){
        jTextFieldCustName.setText("");
        jTextFieldCustPhone.setText("");
        jTextFieldNotes.setText("");
        jTextFieldCustEmail.setText("");
        jTextFieldCustPincode.setText("");
        
    }
    public ArrayList<String> check_empty_field(){
        ArrayList<String> user_input = new ArrayList<>();
        String user_cust_name = jTextFieldCustName.getText();
        String user_cust_phone = jTextFieldCustPhone.getText();
        String user_cust_email = jTextFieldCustEmail.getText();
//        String user_hospital_id = (String) jComboBoxHospitalList.getSelectedItem();
        String user_pincode = jTextFieldCustPincode.getText();
        Date date = jDateChooserTestDate.getDate();
        String user_request_date = new SimpleDateFormat("MM.dd.yyyy").format(date);
//        String user_request_date = jDateChooserTestDate.getDateFormatString();
        String user_cust_notes = jTextFieldNotes.getText();
        
        
        if(user_cust_name.isEmpty()){
            JOptionPane.showMessageDialog(this, "User Name can't be left empty.");
        }
        else if(user_cust_phone.isEmpty()){
            JOptionPane.showMessageDialog(this, "User Phone Number can't be left empty.");
        }
        else if(user_cust_email.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter an email.");
        }

        else if(user_pincode.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter the user pincode");
        }
        else if(user_request_date.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a request date.");
        }
        else if(request_category.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please choose a category.");
        }
        else if(user_cust_notes.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter the request details.");
        }
        
        user_input.add(user_cust_name);
        user_input.add(user_cust_phone);
        user_input.add(user_cust_email);
//        user_input.add(user_hospital_id);
        user_input.add(user_pincode);
        user_input.add(user_request_date);
        user_input.add(request_category);
        user_input.add(user_cust_notes);
        user_input.add("HUMAN");
        return user_input;
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgdimg;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonUpdate;
    private com.toedter.calendar.JDateChooser jDateChooserTestDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEmpID;
    private javax.swing.JLabel jLabelEmpName;
    private javax.swing.JLabel jLabelEmpName1;
    private javax.swing.JLabel jLabelEmpName2;
    private javax.swing.JLabel jLabelEmpName3;
    private javax.swing.JLabel jLabelEmpName5;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JRadioButton jRadioButtonMedEquipment;
    private javax.swing.JRadioButton jRadioButtonMedTest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRequests;
    private javax.swing.JTextField jTextFieldCustEmail;
    private javax.swing.JTextField jTextFieldCustName;
    private javax.swing.JTextField jTextFieldCustPhone;
    private javax.swing.JTextField jTextFieldCustPincode;
    private javax.swing.JTextField jTextFieldNotes;
    // End of variables declaration//GEN-END:variables

    

    private void addrecordstotable() {
    
        DefaultTableModel model = (DefaultTableModel) jTableRequests.getModel();
        model.setRowCount(0);
        RequestDirectory requestDirectory = medicalServiceCentralisationEcoSystem.getRequestDirectory();
        if(requestDirectory!=null){
            ArrayList<Request> requestList = requestDirectory.getRequestList();
            for(Request request: requestList)
            {   
                model.addRow(new Object[]{
                    request,
                    request.getCustomer_name(),
                    request.getCustomer_phone(),
                    request.getCustomer_email(),
                    request.getCustomer_pincode(),
                    request.getRequest_date(),
                    request.getRequest_category(),
                    request.getRequest_description(), 
                    request.getModified_time()});

            }

            jTableRequests.setModel(model);
        }
        
    }
    
    
}
