/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.HospitalManagement.AdministrativeWorkArea;


import userInterface.SystemAdminWorkArea.*;
import java.awt.CardLayout;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterface.HospitalManagementMainJFrame;
/**
 *
 * @author animeshgiri
 */
public class AdminstrativeAccountManagement extends javax.swing.JPanel {

    /**
     * Creates new form MedTechnicalAccountsPage
     */
    JPanel userProcessContainer;
//    EcoSystem ecosystem;
//    CustomerDirectory customerDirectory;
//    RestaurantDirectory restaurantDirectory;
//    UserAccount userAccount;
//    Restaurant restaurant;
//    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
//    
//    public AdminstrativeAccountManagement(JPanel userProcessContainer , EcoSystem ecosystem) {
//        this.userProcessContainer = userProcessContainer;
//        this.ecosystem = ecosystem;
//        initComponents();
//        if(ecosystem.getRestaurantDirectory() == null)
//           ecosystem.setRestaurantDirectory(new RestaurantDirectory());
////        this.ecosystem = dB4OUtil.retrieveSystem();
//        addrecordstotable(2);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jButtonHome = new javax.swing.JButton();
        jTextFieldPatientID = new javax.swing.JTextField();
        jLabelPatientID = new javax.swing.JLabel();
        jLabelPatientName = new javax.swing.JLabel();
        jTextFieldPatientName = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JButton();
        jButtonCreate = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAccounts = new javax.swing.JTable();
        jTextFieldPhoneNum = new javax.swing.JTextField();
        jLabelPhoneNum = new javax.swing.JLabel();
        jLabelInsuaranceNum = new javax.swing.JLabel();
        jTextFieldInsuranceNum = new javax.swing.JTextField();
        jTextFieldConsultationFee = new javax.swing.JTextField();
        jLabelConsultationFee = new javax.swing.JLabel();
        jLabelTestFee = new javax.swing.JLabel();
        jTextFieldTestFee = new javax.swing.JTextField();
        jTextFieldAdmissionFee = new javax.swing.JTextField();
        jLabelAdmissionFee = new javax.swing.JLabel();
        jLabelAmbulanceFee = new javax.swing.JLabel();
        jTextFieldAmbulanceFee = new javax.swing.JTextField();
        jTextFielddDiscount = new javax.swing.JTextField();
        jLabelDiscount = new javax.swing.JLabel();
        jLabelAdvancePaid = new javax.swing.JLabel();
        jTextFieldAdvancePaid = new javax.swing.JTextField();
        jTextFieldAmountDue = new javax.swing.JTextField();
        jLabelAmountDue = new javax.swing.JLabel();
        jLabelPharmacyBill = new javax.swing.JLabel();
        jTextFieldPharmacyBill = new javax.swing.JTextField();
        jTextFieldICUServices = new javax.swing.JTextField();
        jLabelICUServices = new javax.swing.JLabel();
        jLabelMedicalEquipment = new javax.swing.JLabel();
        jTextFieldMedicalEquipment = new javax.swing.JTextField();
        jTextFieldRoomRentServices = new javax.swing.JTextField();
        jLabelRoomRentServices = new javax.swing.JLabel();
        jLabelNursingCharges = new javax.swing.JLabel();
        jTextFieldNursingCharges = new javax.swing.JTextField();
        jTextFieldEmpID8 = new javax.swing.JTextField();
        jLabelTAX = new javax.swing.JLabel();
        jLabelGrandTotal = new javax.swing.JLabel();
        jTextFieldGrandTotal = new javax.swing.JTextField();
        jLabelSubTitle = new javax.swing.JLabel();
        jButtonSearch = new javax.swing.JButton();
        jButtonAddtoCart = new javax.swing.JButton();
        jButtonCheckout = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1181, 1080));

        jPanel1.setBackground(new java.awt.Color(0, 70, 169));
        jPanel1.setPreferredSize(new java.awt.Dimension(1381, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabelTitle.setBackground(new java.awt.Color(0, 70, 169));
        jLabelTitle.setFont(new java.awt.Font("Times New Roman", 1, 56)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("ACCOUNTS MANAGEMENT");

        jButtonHome.setBackground(new java.awt.Color(0, 70, 169));
        jButtonHome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonHome.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome.setText("HOME");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jTextFieldPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPatientIDActionPerformed(evt);
            }
        });

        jLabelPatientID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPatientID.setText("Patient ID :");

        jLabelPatientName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPatientName.setText("Patient Name:");

        jButtonDelete.setBackground(new java.awt.Color(255, 255, 204));
        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDelete.setText("DELETE");

        jButtonCreate.setBackground(new java.awt.Color(255, 255, 204));
        jButtonCreate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCreate.setText("CREATE");

        jButtonUpdate.setBackground(new java.awt.Color(255, 255, 204));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonUpdate.setText("UPDATE");

        jButtonView.setBackground(new java.awt.Color(255, 255, 204));
        jButtonView.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonView.setText("VIEW");

        jTableAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Consulation Fee", "$60"},
                {"2", "Test Fee", "$50"},
                {"3", "Admission Fee", "$400"},
                {"4", "Ambulance Fee", "$200"},
                {"5", "Pharmacy Bill", "$80"},
                {"6", "ICU Services", "$1500"},
                {"7", "Medical Equipment", "$250"},
                {"8", "Room Rent ", "$300"},
                {"9", "Nursing Charges", "$100"},
                {"10", "Surgery Cost", "$3000"}
            },
            new String [] {
                "S.no", "Fee Particulars", "Cost"
            }
        ));
        jScrollPane1.setViewportView(jTableAccounts);

        jTextFieldPhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneNumActionPerformed(evt);
            }
        });

        jLabelPhoneNum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPhoneNum.setText("Phone Number :");

        jLabelInsuaranceNum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelInsuaranceNum.setText("Insurance Number :");

        jTextFieldConsultationFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConsultationFeeActionPerformed(evt);
            }
        });

        jLabelConsultationFee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelConsultationFee.setText("Consultation Fee : ");

        jLabelTestFee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTestFee.setText("Test Fee :");

        jTextFieldAdmissionFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAdmissionFeeActionPerformed(evt);
            }
        });

        jLabelAdmissionFee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAdmissionFee.setText("Admission Charges :");

        jLabelAmbulanceFee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAmbulanceFee.setText("Ambulance Fee :");

        jTextFielddDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddDiscountActionPerformed(evt);
            }
        });

        jLabelDiscount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDiscount.setText("Discount Applied :");

        jLabelAdvancePaid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAdvancePaid.setText("Advance Paid :");

        jTextFieldAmountDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAmountDueActionPerformed(evt);
            }
        });

        jLabelAmountDue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAmountDue.setText("Amount Due :");

        jLabelPharmacyBill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPharmacyBill.setText("Pharmacy Bill :");

        jTextFieldICUServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldICUServicesActionPerformed(evt);
            }
        });

        jLabelICUServices.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelICUServices.setText("ICU Services :");

        jLabelMedicalEquipment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMedicalEquipment.setText("Medical Equipment :");

        jTextFieldRoomRentServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRoomRentServicesActionPerformed(evt);
            }
        });

        jLabelRoomRentServices.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelRoomRentServices.setText("Room Rent Service :");

        jLabelNursingCharges.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNursingCharges.setText("Nursing Charges :");

        jTextFieldEmpID8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmpID8ActionPerformed(evt);
            }
        });

        jLabelTAX.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTAX.setText("TAX :");

        jLabelGrandTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelGrandTotal.setText("Grand Total :");

        jLabelSubTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelSubTitle.setText("FEE PARTICULARS");

        jButtonSearch.setBackground(new java.awt.Color(255, 255, 204));
        jButtonSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSearch.setText("SEARCH");

        jButtonAddtoCart.setBackground(new java.awt.Color(255, 255, 204));
        jButtonAddtoCart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAddtoCart.setText("Add to Cart");

        jButtonCheckout.setBackground(new java.awt.Color(255, 255, 204));
        jButtonCheckout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCheckout.setText("Checkout");
        jButtonCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPatientName)
                    .addComponent(jLabelPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jLabelPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jLabelInsuaranceNum, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldInsuranceNum, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jButtonHome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jButtonAddtoCart)
                        .addGap(351, 351, 351)
                        .addComponent(jButtonCheckout)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabelConsultationFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelRoomRentServices, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabelAdmissionFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(jLabelTestFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabelAmbulanceFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabelPharmacyBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(jLabelICUServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabelMedicalEquipment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabelNursingCharges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(11, 11, 11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabelDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldEmpID8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldNursingCharges, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFielddDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonView, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldMedicalEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldConsultationFee, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(124, 124, 124)
                                        .addComponent(jLabelAdvancePaid))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldTestFee, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldAdmissionFee, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(124, 124, 124)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelGrandTotal)
                                            .addComponent(jLabelAmountDue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAmountDue, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jTextFieldAdvancePaid)
                                    .addComponent(jTextFieldGrandTotal)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPharmacyBill, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAmbulanceFee, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldICUServices, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldRoomRentServices, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(207, 207, 207)
                        .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabelTAX, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabelSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldPatientID, jTextFieldPatientName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldInsuranceNum, jTextFieldPhoneNum});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldAdmissionFee, jTextFieldAmbulanceFee, jTextFieldConsultationFee, jTextFieldTestFee});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldICUServices, jTextFieldMedicalEquipment, jTextFieldPharmacyBill, jTextFieldRoomRentServices});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldEmpID8, jTextFieldNursingCharges, jTextFielddDiscount});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCreate, jButtonDelete, jButtonUpdate, jButtonView});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabelTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButtonHome)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPatientID)
                    .addComponent(jLabelPhoneNum)
                    .addComponent(jTextFieldPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPatientName)
                    .addComponent(jTextFieldPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInsuaranceNum)
                    .addComponent(jTextFieldInsuranceNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabelSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldConsultationFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelConsultationFee, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelAdvancePaid)
                                    .addComponent(jTextFieldAdvancePaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldTestFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTestFee)
                                    .addComponent(jTextFieldAmountDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAmountDue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAdmissionFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAdmissionFee)
                            .addComponent(jLabelGrandTotal)
                            .addComponent(jTextFieldGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAmbulanceFee)
                    .addComponent(jTextFieldAmbulanceFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPharmacyBill)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelICUServices, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldICUServices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldPharmacyBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMedicalEquipment)
                    .addComponent(jTextFieldMedicalEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRoomRentServices)
                    .addComponent(jTextFieldRoomRentServices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNursingCharges)
                    .addComponent(jTextFieldNursingCharges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEmpID8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTAX))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFielddDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAddtoCart)
                            .addComponent(jButtonCheckout)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonView, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldPatientID, jTextFieldPatientName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldInsuranceNum, jTextFieldPhoneNum});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelAdmissionFee, jLabelAmbulanceFee, jLabelConsultationFee, jLabelICUServices, jLabelMedicalEquipment, jLabelNursingCharges, jLabelPharmacyBill, jLabelRoomRentServices, jLabelTestFee});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldAdmissionFee, jTextFieldAmbulanceFee, jTextFieldConsultationFee, jTextFieldTestFee});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldICUServices, jTextFieldMedicalEquipment, jTextFieldPharmacyBill, jTextFieldRoomRentServices});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldAdvancePaid, jTextFieldAmountDue, jTextFieldGrandTotal});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonCreate, jButtonDelete, jButtonUpdate, jButtonView});

    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
            crdLyt.show(userProcessContainer,"Sysadmin");
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jTextFieldPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPatientIDActionPerformed

    private void jTextFieldPhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneNumActionPerformed

    private void jTextFieldConsultationFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConsultationFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConsultationFeeActionPerformed

    private void jTextFieldAdmissionFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAdmissionFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdmissionFeeActionPerformed

    private void jTextFielddDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddDiscountActionPerformed

    private void jTextFieldAmountDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAmountDueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAmountDueActionPerformed

    private void jTextFieldICUServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldICUServicesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldICUServicesActionPerformed

    private void jTextFieldRoomRentServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRoomRentServicesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRoomRentServicesActionPerformed

    private void jTextFieldEmpID8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmpID8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmpID8ActionPerformed

    private void jButtonCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCheckoutActionPerformed
    /*private void clearFields(){
        restaurantID.setText("");
        restaurantName.setText("");
        restaurantPincode.setText("");
        restaurantPhone.setText("");
        restaurantPassword.setText("");
    }
    public ArrayList<String> check_empty_field(){
        ArrayList<String> user_input = new ArrayList<>();
        String user_rest_id = restaurantID.getText();
        String user_rest_name = restaurantName.getText();
        String user_pincode = restaurantPincode.getText();
        String user_contact_no = restaurantPhone.getText();
        String user_password = restaurantPassword.getText();
        
        
        if(user_rest_id.isEmpty()){
            JOptionPane.showMessageDialog(this, "Restaurant ID can't be left empty.");
        }
        else if(user_rest_name.isEmpty()){
            JOptionPane.showMessageDialog(this, "Restaurant Name can't be left empty.");
        }
        else if(user_pincode.isEmpty()){
            JOptionPane.showMessageDialog(this, "Restaurant Pincode can't be left empty.");
        }
        else if(user_contact_no.isEmpty()){
            JOptionPane.showMessageDialog(this, "Restaurant Contact No can't be left empty.");
        }
        else if(user_password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a Password.");
        }
        
        
        user_input.add(user_rest_id);
        user_input.add(user_rest_name);
        user_input.add(user_pincode);
        user_input.add(user_contact_no);
        user_input.add(user_password);
        
        return user_input;
        
    }
    private Restaurant set_user_input_values(Restaurant restaurant, ArrayList<String> user_input){
        
        restaurant.setRest_id(user_input.get(0));
        restaurant.setName(user_input.get(1));
        restaurant.setRest_pincode(user_input.get(2));
        restaurant.setContact_no(user_input.get(3));
        return restaurant;
    }
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddtoCart;
    private javax.swing.JButton jButtonCheckout;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonView;
    private javax.swing.JLabel jLabelAdmissionFee;
    private javax.swing.JLabel jLabelAdvancePaid;
    private javax.swing.JLabel jLabelAmbulanceFee;
    private javax.swing.JLabel jLabelAmountDue;
    private javax.swing.JLabel jLabelConsultationFee;
    private javax.swing.JLabel jLabelDiscount;
    private javax.swing.JLabel jLabelGrandTotal;
    private javax.swing.JLabel jLabelICUServices;
    private javax.swing.JLabel jLabelInsuaranceNum;
    private javax.swing.JLabel jLabelMedicalEquipment;
    private javax.swing.JLabel jLabelNursingCharges;
    private javax.swing.JLabel jLabelPatientID;
    private javax.swing.JLabel jLabelPatientName;
    private javax.swing.JLabel jLabelPharmacyBill;
    private javax.swing.JLabel jLabelPhoneNum;
    private javax.swing.JLabel jLabelRoomRentServices;
    private javax.swing.JLabel jLabelSubTitle;
    private javax.swing.JLabel jLabelTAX;
    private javax.swing.JLabel jLabelTestFee;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAccounts;
    private javax.swing.JTextField jTextFieldAdmissionFee;
    private javax.swing.JTextField jTextFieldAdvancePaid;
    private javax.swing.JTextField jTextFieldAmbulanceFee;
    private javax.swing.JTextField jTextFieldAmountDue;
    private javax.swing.JTextField jTextFieldConsultationFee;
    private javax.swing.JTextField jTextFieldEmpID8;
    private javax.swing.JTextField jTextFieldGrandTotal;
    private javax.swing.JTextField jTextFieldICUServices;
    private javax.swing.JTextField jTextFieldInsuranceNum;
    private javax.swing.JTextField jTextFieldMedicalEquipment;
    private javax.swing.JTextField jTextFieldNursingCharges;
    private javax.swing.JTextField jTextFieldPatientID;
    private javax.swing.JTextField jTextFieldPatientName;
    private javax.swing.JTextField jTextFieldPharmacyBill;
    private javax.swing.JTextField jTextFieldPhoneNum;
    private javax.swing.JTextField jTextFieldRoomRentServices;
    private javax.swing.JTextField jTextFieldTestFee;
    private javax.swing.JTextField jTextFielddDiscount;
    // End of variables declaration//GEN-END:variables
/*
    private void addrecordstotable(int par) {
        restaurantDirectory = ecosystem.getRestaurantDirectory();
        DefaultTableModel model = (DefaultTableModel) RestaurantsTable.getModel();
//        DefaultComboBo/xModel dc = new DefaultComboBoxModel();
        model.setRowCount(0);
        ArrayList<Restaurant> restaurants = restaurantDirectory.getRestaurantList();
        for(Restaurant r: restaurants)
        {
            model.addRow(new Object[]{r,r.getName(),r.getContact_no(),r.getRest_pincode(),r.getUserAccount().getPassword()});
        }
        RestaurantsTable.setModel(model);
        dB4OUtil.storeSystem(ecosystem);
    }
}
*/
}