/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.HospitalManagement.OperationalWorkArea;


import userInterface.SystemAdminWorkArea.*;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author animeshgiri
 */
public class OperationalPatientEncounter extends javax.swing.JPanel {

    /**
     * Creates new form OperationalAccountsPage
     */
    JPanel userProcessContainer;
    public OperationalPatientEncounter(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
    }
    /*EcoSystem ecosystem;
    CustomerDirectory customerDirectory;
    UserAccount userAccount;
    Customer customer;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public OperationalPatientEncounter(JPanel userProcessContainer , EcoSystem ecosystem) {
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
//        this.ecosystem = dB4OUtil.retrieveSystem();
        if(ecosystem.getCustomerDirectory() == null)
           ecosystem.setCustomerDirectory(new CustomerDirectory());
        initComponents();
        populateTable();
    }
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jButtonDownloadPrescription = new javax.swing.JButton();
        jButtonCreate = new javax.swing.JButton();
        jTextFieldPatientName = new javax.swing.JTextField();
        jTextFieldPatientID = new javax.swing.JTextField();
        jLabelPatientID = new javax.swing.JLabel();
        jLabelPatientName = new javax.swing.JLabel();
        jTextFieldBloodGroup = new javax.swing.JTextField();
        jTextFieldAge = new javax.swing.JTextField();
        jLabelAge = new javax.swing.JLabel();
        jLabelBloodGroup = new javax.swing.JLabel();
        jTextFieldPulse = new javax.swing.JTextField();
        jTextFieldBloodPressure = new javax.swing.JTextField();
        jLabelDiagnosisandPrescription = new javax.swing.JLabel();
        jLabelPulse = new javax.swing.JLabel();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jTextFieldGender = new javax.swing.JTextField();
        jLabelGender = new javax.swing.JLabel();
        jLabelPhoneNumber = new javax.swing.JLabel();
        jTextFieldWeight = new javax.swing.JTextField();
        jTextFieldHeight = new javax.swing.JTextField();
        jLabelHeight = new javax.swing.JLabel();
        jLabelEmpName4 = new javax.swing.JLabel();
        jTextFieldTemparature = new javax.swing.JTextField();
        jTextFieldBMI = new javax.swing.JTextField();
        jLabelBMI = new javax.swing.JLabel();
        jLabelTemparature = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDiagnosisandPrescription = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaReasonForVisit = new javax.swing.JTextArea();
        jLabelBloodPressure = new javax.swing.JLabel();
        jLabelReasonforVisit = new javax.swing.JLabel();
        jLabelAllergies = new javax.swing.JLabel();
        jTextFieldAllergies = new javax.swing.JTextField();
        jButtonDownloadPrescription1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Patient Encounter");
        add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 706, -1));

        jButtonDownloadPrescription.setBackground(new java.awt.Color(255, 255, 204));
        jButtonDownloadPrescription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDownloadPrescription.setText("Email prescription");
        add(jButtonDownloadPrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 620, -1, -1));

        jButtonCreate.setText("SUBMIT");
        add(jButtonCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 910, 100, 30));
        add(jTextFieldPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 140, -1));
        add(jTextFieldPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 140, -1));

        jLabelPatientID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPatientID.setText("Patient ID:");
        add(jLabelPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 150, 20));

        jLabelPatientName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPatientName.setText("Patient Name:");
        add(jLabelPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 150, 20));
        add(jTextFieldBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 140, -1));
        add(jTextFieldAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 140, -1));

        jLabelAge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAge.setText("Age :");
        add(jLabelAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 80, 20));

        jLabelBloodGroup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelBloodGroup.setText("Blood Group :");
        add(jLabelBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 130, 20));
        add(jTextFieldPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 140, -1));
        add(jTextFieldBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 140, -1));

        jLabelDiagnosisandPrescription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDiagnosisandPrescription.setText("Diagnosis and Prescription :");
        add(jLabelDiagnosisandPrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 260, 20));

        jLabelPulse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPulse.setText("Pulse :");
        add(jLabelPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 100, 20));
        add(jTextFieldPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 140, -1));
        add(jTextFieldGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 140, -1));

        jLabelGender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelGender.setText("Gender :");
        add(jLabelGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 104, -1));

        jLabelPhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPhoneNumber.setText("Phone Number :");
        add(jLabelPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));
        add(jTextFieldWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 140, -1));
        add(jTextFieldHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 140, -1));

        jLabelHeight.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelHeight.setText("Height :");
        add(jLabelHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 104, -1));

        jLabelEmpName4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEmpName4.setText("Weight :");
        add(jLabelEmpName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));
        add(jTextFieldTemparature, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 140, -1));
        add(jTextFieldBMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 140, -1));

        jLabelBMI.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelBMI.setText("B.M.I. :");
        add(jLabelBMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 80, 20));

        jLabelTemparature.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTemparature.setText("Temperature :");
        add(jLabelTemparature, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        jTextAreaDiagnosisandPrescription.setColumns(20);
        jTextAreaDiagnosisandPrescription.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDiagnosisandPrescription);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 420, 40));

        jTextAreaReasonForVisit.setColumns(20);
        jTextAreaReasonForVisit.setRows(5);
        jScrollPane3.setViewportView(jTextAreaReasonForVisit);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 420, 40));

        jLabelBloodPressure.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelBloodPressure.setText("Blood Pressure :");
        add(jLabelBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 150, 20));

        jLabelReasonforVisit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelReasonforVisit.setText("Reason for Visit :");
        add(jLabelReasonforVisit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 190, 20));

        jLabelAllergies.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAllergies.setText("Allergies :");
        add(jLabelAllergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 170, 20));
        add(jTextFieldAllergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 552, 240, 30));

        jButtonDownloadPrescription1.setBackground(new java.awt.Color(255, 255, 204));
        jButtonDownloadPrescription1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDownloadPrescription1.setText("Download prescription");
        jButtonDownloadPrescription1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownloadPrescription1ActionPerformed(evt);
            }
        });
        add(jButtonDownloadPrescription1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 620, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDownloadPrescription1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownloadPrescription1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDownloadPrescription1ActionPerformed
    /*private Customer set_user_input_values(Customer customer, ArrayList<String> user_input){
        
        customer.getUserAccount().setPassword(user_input.get(1));
        customer.setCustomerPhone(user_input.get(2));
        return customer;
    }
        private void clearFields(){
        custUsername.setText("");
        custPassword.setText("");
        custContact.setText("");

    }
    public ArrayList<String> check_empty_field(){
        ArrayList<String> user_input = new ArrayList<>();
        String user_custName = custUsername.getText();
        String user_custPass = custPassword.getText();
        String user_contact = custContact.getText();
 
        if(user_custName.isEmpty()){
            JOptionPane.showMessageDialog(this, "Customer Name can't be left empty");
        }
        else if(user_custPass.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter password");
        }
        
        else if(user_contact.isEmpty()){
            JOptionPane.showMessageDialog(this, "Customer Contact No can't be left empty.");
        }
        user_input.add(user_custName);
        user_input.add(user_custPass);
        user_input.add(user_contact);
        
        return user_input;
        
    }
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonDownloadPrescription;
    private javax.swing.JButton jButtonDownloadPrescription1;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelAllergies;
    private javax.swing.JLabel jLabelBMI;
    private javax.swing.JLabel jLabelBloodGroup;
    private javax.swing.JLabel jLabelBloodPressure;
    private javax.swing.JLabel jLabelDiagnosisandPrescription;
    private javax.swing.JLabel jLabelEmpName4;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelHeight;
    private javax.swing.JLabel jLabelPatientID;
    private javax.swing.JLabel jLabelPatientName;
    private javax.swing.JLabel jLabelPhoneNumber;
    private javax.swing.JLabel jLabelPulse;
    private javax.swing.JLabel jLabelReasonforVisit;
    private javax.swing.JLabel jLabelTemparature;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaDiagnosisandPrescription;
    private javax.swing.JTextArea jTextAreaReasonForVisit;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldAllergies;
    private javax.swing.JTextField jTextFieldBMI;
    private javax.swing.JTextField jTextFieldBloodGroup;
    private javax.swing.JTextField jTextFieldBloodPressure;
    private javax.swing.JTextField jTextFieldGender;
    private javax.swing.JTextField jTextFieldHeight;
    private javax.swing.JTextField jTextFieldPatientID;
    private javax.swing.JTextField jTextFieldPatientName;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JTextField jTextFieldPulse;
    private javax.swing.JTextField jTextFieldTemparature;
    private javax.swing.JTextField jTextFieldWeight;
    // End of variables declaration//GEN-END:variables
/*
    private void populateTable() {
        
        customerDirectory = ecosystem.getCustomerDirectory();
        ArrayList<Customer> customers = customerDirectory.getCustomerList();
        DefaultTableModel model = (DefaultTableModel) customersTable.getModel();
        model.setRowCount(0);
//        DefaultComboBoxModel dc = new DefaultComboBoxModel();
        
        for(Customer c: customers)
        {
            model.addRow(new Object[]{c,c.getUserAccount().getPassword(), c.getCustomerPhone()});
//            dc.addElement(c.getCustomerName());
        }
        customersTable.setModel(model);
//        listCustomers.setModel(dc);
        dB4OUtil.storeSystem(ecosystem);
    }*/
}
